### ISSUE TITLE
Logging Enhancement

### ISSUE THREAD

**Issue by Sonubairagi** [Sonubairagi/Xplore#4]
# **logging**

## **Tasks**

- logs should be design and write in a way where it can be easy and fast to find any specific error/exception/problem if any API execution got failed for any particular user and by any reason.
- [ ] team should able to find which API execution got failed and why?
- [ ] team should able to find which user faced this problem/error/exception.
- [ ] prepare a error response where user will get all details about error/exception with a correlationID which related to API/request which got failed. So, later user will report the issue to our support team by providing this Id and then we will use this id to filter the logs, In result we will get only user, api/request and error related logs which help us to find the issue faster.

**Comment by Tarunvairagi** [comment]
**I thing this task was completed.** So you can close the task and give me the any other task!

**Comment by Sonubairagi** [comment]
@Tarunvairagi , this is not accepted from a 3 years experience guy, why you close this task

**Comment by Tarunvairagi** [comment]
**Okay!**
This is **my fault** _I was read the task explanation wrong way_ so I was closed the task **sorry!**
you can **reopen** the task then I will start the work!.
**Thankyou!**

**Comment by Sonubairagi** [comment]
I wonder how you read a simple text wrongly this is the basic think tarun, what you think that we are here to re-open issue again and again. this is last time i m telling you. be careful from next time
I'll re open now
please provide the estimation

**Comment by Tarunvairagi** [comment]
**Right!** I reading the task related information and my thinking was wrong because you ware provided similar task already so I was you are say to me we are close the task and I was not read properly and I was closed the task so that is the reason.
**_I am really really sorry..._**
This is my **bad** I'll take cate of it _next time!_

**Comment by Tarunvairagi** [comment]
> # **logging**
> ## **Tasks**
> * logs should be design and write in a way where it can be easy and fast to find any specific error/exception/problem if any API execution got failed for any particular user and by any reason.
> * [ ]  team should able to find which API execution got failed and why?
> * [ ]  team should able to find which user faced this problem/error/exception.
> * [ ]  prepare a error response where user will get all details about error/exception with a correlationID which related to API/request which got failed. So, later user will report the issue to our support team by providing this Id and then we will use this id to filter the logs, In result we will get only user, api/request and error related logs which help us to find the issue faster.

**Okay!** I understand this task what are doing actual you can give me some suggestion how to achieve that and I have one solution 
1. firstly I am create a unique UUID in the controller so user fire the API then which API is call and which user is calling the API that
   API ID and Username store one variable and set the all the process. 
2. User fire the URL and generate the error or exception so generate the ID and getting username then we are take the 
   information and find that
**_Like this :_**
29-12-2024 00:13:31 - INFO - c.xplore.controller.UserController - Entering getUser with User: mike : API ID : eebbc881-1e57-4796-bd54-9e68fe7479ef USERNAME : mike sign-up API
29-12-2024 00:13:57 - INFO - c.xplore.controller.UserController - Entering getUser with User: test : API ID : 09537f90-894f-423e-8344-83c9d1b44a94 USERNAME : test sign-up API
29-12-2024 00:14:30 - INFO - c.xplore.controller.UserController - Entering getUser with User: mike : API ID : c969804c-5047-4900-9489-704853df54bc USERNAME : mike sign-up API
29-12-2024 00:14:38 - INFO - c.xplore.controller.UserController - Successfully retrieved profile image: profileImage, API ID : c969804c-5047-4900-9489-704853df54bc USERNAME : mike, sign-up API
29-12-2024 00:14:42 - DEBUG - com.xplore.service.UserServiceImpl - Processing user with user object: mike@gmail.com
29-12-2024 00:14:46 - WARN - com.xplore.service.UserServiceImpl - Warning! User Already Exists: mike
29-12-2024 00:13:38 - ERROR - c.xplore.controller.UserController - Failed! to retrieve user profile image: Image is not getting! :  API ID : eebbc881-1e57-4796-bd54-9e68fe7479ef USERNAME : mike sign-up API

**This are some logs I was test developed only testing purpose so I ask you that process is good or not?**

**Comment by Tarunvairagi** [comment]
Okay! Today I was committed by id **`86e6a67f0ca9d51b6eed974c10b3b94fc86652fe`** the complete the task. 
you can review the code and if any error/bugs  you can inform to me then I will fix that! 
Thankyou!
